version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:20.10

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Run Security Audit
          command: npm audit --audit-level=high || true

      - run:
          name: Verify Backend
          command: node backend/server.js

workflows:
  version: 2
  build_and_test:
    jobs:
      - build